version: "3"

services:
  authserver:
    restart: always
    build: ./authserver
    expose:
      - "8080"
    links:
      - maria:maria
    environment:
      - DB_HOSTNAME=maria
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root

  lobbyserver:
    restart: always
    build: ./lobbyserver
    expose:
      - "8080"

  quizserver:
    restart: always
    build: ./quizserver
    expose:
      - "8080"
    links:
      - maria:maria
    environment:
      - DB_HOSTNAME=maria
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root

  client:
    build: ../client/client01
    volumes:
      - /app/dist

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
      - web-logs:/var/log/nginx
    volumes_from:
      - client
    links:
      - authserver:authserver
      - lobbyserver:lobbyserver
      - quizserver:quizserver
      - client:client

  maria:
    restart: always
    image: mariadb:latest
    expose:
      - "3306"
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=quizduell

volumes:
  web-static:
  web-logs:
